trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureStaticWebApp@0
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/src/Future030.MiniApp.GatedContentArea.Client.'
    app_location: '.'
    app_build_command: 'dotnet publish -c Release -o bin'
    output_location: 'bin/wwwroot'
    azure_static_web_apps_api_token: '$(DEPLOYMENT_TOKEN)'