trigger:
- main

pool:
  vmImage: ubuntu-22.04

steps:
  - task: UseDotNet@2
    displayName: "Install .NET SDK"
    inputs:
      packageType: "sdk"
      version: "8.x"

  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: "20.x"

  - script: |
      npm install -g @azure/static-web-apps-cli
      cd src/Future030.MiniApp.GatedContentArea.Client
      swa build
      swa deploy --env Production --deployment-token $(DEPLOYMENT_TOKEN)
    displayName: "Build & Deploy using swa-cli"