trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  app_location: "src/Future030.MiniApp.GatedContentArea.Client"
  output_location: "bin/wwwroot"

steps:
  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: "20.x"

  - task: AzureStaticWebApp@0
    displayName: "Deploy to Azure Static Web Apps"
    inputs:
      app_location: "$(app_location)"
      output_location: "$(output_location)"
      app_build_command: "dotnet publish -c Release -o bin"
      azure_static_web_apps_api_token: "$(DEPLOYMENT_TOKEN)"